### PR TITLE
[DOC] Added my blog post

### PR DESCRIPTION
**Pull request by carlos-silvap**
Generated new .md file

### CODE REVIEW

**Review by LauRivero150920 — DISMISSED** [review]
Nice Job! :3

**Review by CristianCazares — DISMISSED** [review]
Nice

**Review by lemontyc — DISMISSED** [review]

**Review by lemontyc — APPROVED** [review]

**Review by CristianCazares — APPROVED** [review]
Nice

**Review by LuisAGuzmanI — APPROVED** [review]
Nice

**Pull request merged**
